name: firestore_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  change_app_package_name: ^1.4.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
